name: Java CI

on: [push]

jobs:
  build_and_stage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 14.0.1
        uses: actions/setup-java@v1
        with:
          java-version: 14.0.1

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Copy jar file to Staging
        run: mkdir staging && cp target/*.jar staging
        
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
          
       
  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: build_and_stage
    name: Docker Build, Tag, Push

    steps:
    - name: Download built artifact
      uses: actions/download-artifact@v2
      with:
        name: Package
        path: staging
        
    - name: Display downloaded files
      run: ls -R
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
       
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and Push docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: user/app:latest
       